services:
  database:
    image: postgres
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=fin_api
    volumes:
      - db-data:/data/postgres:rw
    ports:
      - 5432:5432

volumes:
  db-data:
    driver: local